# Generated by Django 4.1.1 on 2022-10-06 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('lastName', models.CharField(max_length=30, verbose_name='LastName')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('gender', models.CharField(blank=True, max_length=50, verbose_name='Gender')),
                ('role', models.IntegerField(verbose_name='Role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('direction', models.CharField(max_length=100, verbose_name='Direction')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('dateOfBirth', models.DateField(verbose_name='dateOfBirth')),
                ('latitude', models.CharField(blank=True, max_length=50, verbose_name='Latitude')),
                ('length', models.CharField(blank=True, max_length=50, verbose_name='Length')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_std', to=settings.AUTH_USER_MODEL)),
                ('medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_std', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('specialty', models.CharField(max_length=100, verbose_name='Specialty')),
                ('registration', models.CharField(max_length=255, verbose_name='Registration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('relationship', models.CharField(max_length=50, verbose_name='Relationship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
